### ISSUE TITLE
Issues with install

### ISSUE THREAD

**Issue by bossanova808** [nystudio107/craft3-instantanalytics#12]
Ok, so my general process is to upgrade a db from Craft 2 -> 3 and the in my own little custom console controller I have:

`
Craft::$app->plugins->installPlugin('instant-analytics');
`
...this does not raise an error.  But it also (unlike with several other plugins I do this with) - does not results in the plugin being installed.

So I have to go into the control panel and manually install it there in the plugins section.  Then I immediately get this error:

![image](https://user-images.githubusercontent.com/731309/56552551-03544200-65cf-11e9-915d-e0f7cb66eb82.png)

..because, again unlike any other plugin, it is in 'Disabled' state after the initial install.  When I then enable it, it then works as expected.

**Comment by khalwat** [comment]
Is this controller being run via a console command @bossanova808 ?
