### ISSUE TITLE
Getting unknown property: craft\commerce\elements\Product::product

### ISSUE THREAD

**Issue by MarcelWeidum** [nystudio107/craft3-instantanalytics#13]
`2019-04-26 14:17:57 [-][1][526v3r8o62189l63qvmqq5lp16][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\commerce\elements\Product::product in /data/home/site/public_html/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /data/home/site/public_html/vendor/craftcms/cms/src/base/Element.php(830): yii\base\Component->__get('product')
#1 /data/home/site/public_html/vendor/nystudio107/craft-instantanalytics/src/services/Commerce.php(474): craft\base\Element->__get('product')
#2 /data/home/site/public_html/vendor/nystudio107/craft-instantanalytics/src/services/Commerce.php(224): nystudio107\instantanalytics\services\Commerce->pullDataFromField(Object(craft\commerce\elements\Product), 'ean')
#3 /data/home/site/public_html/vendor/nystudio107/craft-instantanalytics/src/services/Commerce.php(86): nystudio107\instantanalytics\services\Commerce->addProductDataFromLineItem(Object(nystudio107\instantanalytics\helpers\IAnalytics), Object(craft\commerce\models\LineItem))
#4 /data/home/site/public_html/vendor/nystudio107/craft-instantanalytics/src/InstantAnalytics.php(283): nystudio107\instantanalytics\services\Commerce->addToCart(Object(craft\commerce\elements\Order), Object(craft\commerce\models\LineItem))
#5 [internal function]: nystudio107\instantanalytics\InstantAnalytics->nystudio107\instantanalytics\{closure}(Object(craft\commerce\events\LineItemEvent))`

**Comment by khalwat** [comment]
fixed in 1.1.1 -> https://github.com/nystudio107/craft-instantanalytics/releases/tag/1.1.1
