### ISSUE TITLE
Fresh installation gives an TypeError 

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-instantanalytics#16]
Installed via CLI, activated, clicking settings, gives:

![Screenshot 2019-08-07 at 17 07 39](https://user-images.githubusercontent.com/1286410/62634575-6f687500-b936-11e9-88db-30cf99ed346f.jpg)

Craft CMS 3.2.7

**Comment by mylesthedev** [comment]
This happens when you don't have any fields in any of your product types.

@khalwat I think a lot of us install all plugins before adding content etc so maybe a simple check for fields would solve this particular case.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-instantanalytics/releases/tag/1.1.2
