### ISSUE TITLE
instantanalytics url not redirecting to asset url.

### ISSUE THREAD

**Issue by knynkwl** [nystudio107/craft3-instantanalytics#20]
On our production site, the url isn't redirecting to the asset url, it's just giving a blank white screen. It's working on our local env.

**Comment by knynkwl** [comment]
Is there a reason or server config that would be disabling the redirect?

**Comment by khalwat** [comment]
This is going to be some kind of server config issue if it is working in local dev, but not on production.

What specifically it is, I don't have enough information to assist you with.

Can you note your production environment, and the differences between your production environment and your local dev environment?

**Comment by knynkwl** [comment]
We are hosted on Acrustech, and I'm just using MAMP as my local ENV.

**Comment by knynkwl** [comment]
Hey coming back to this. On our staging site, I am getting: 

```
400
Invalid data received for parameter "eventValue".
```

Is there something I am doing wrong?

I am adding
```
<a href="{{ eventTrackingUrl(url, resource.title, "click", "label", "resource")}}" ></a>

**Comment by khalwat** [comment]
Sorry @knynkwl I lost track of this one, I will have a look at this; someone else mentioned they were having this issue as well.

**Comment by uaextension** [comment]
> Sorry @knynkwl I lost track of this one, I will have a look at this; someone else mentioned they were having this issue as well.

It was me! We've been experiencing a blank screen issue with both eventTrackingUrl() and pageViewTrackingUrl()
Example of a generated URL: https://ext.ualberta.ca/instantanalytics/eventTrack/view?url=https%3A//drive.google.com/file/d/0B1qTKpPMGo0eZFhVdThJUUhuODQ/view%3Fusp%3Dsharing&eventCategory=link&eventAction=click&eventLabel=test&eventValue=0

- general.php / .env: 'production' mode; with the devMode set as both true and false. 
- Craft Pro 3.3.15, Instant Analytics 1.1.7
- PHP 7.2.24, Linux 4.15, MySQL 5.7.30

If there are any other config settings that I could share to make debugging possible just let me know.
