### ISSUE TITLE
What is the brand & Product Category fields

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft3-instantanalytics#23]
I'm testing your analytics plugin a little.

I don't understand those two fields:

![Bildschirmfoto 2020-01-03 um 12 49 17](https://user-images.githubusercontent.com/762213/71722065-d88ddf00-2e27-11ea-81fa-00713f09c485.png)

I especially don't understand them because the choice of available fields seems strange.

![Bildschirmfoto 2020-01-03 um 12 52 45](https://user-images.githubusercontent.com/762213/71722083-f4918080-2e27-11ea-9fe4-b929cc42f450.png)

My products don't have a category there is just `Product 1` `Product 2` `Product 3` and so on.
Shouldn't there be just product title available as well?

**Comment by khalwat** [comment]
Brand and Category are used in separate places in the Google Analytics data that is send along.

The brand is the brand name, e.g. "Adidas" and the Category is a category for the thing, e.g. "Shoes"
