### ISSUE TITLE
Cache Warmer counts in instantanalytics

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft3-instantanalytics#24]
I use Instant analytics alongside static [Blitz cache](https://putyourlightson.com/plugins/blitz).

Instantanalytics takes the requests of the cache warmer into it. See [this issue](https://github.com/putyourlightson/craft-blitz/issues/156)

Is there a possibility somehow to prevent this?

**Comment by khalwat** [comment]
I don't think you can use these two together... if there is no server-side execution due to Blitz's static caching, then there is no analytics tracking from Instant Analytics.

If you use Blitz, you're going to need to do your analytics tracking on the frontend via JavaScript.

**Comment by kaspar-allenbach** [comment]
I think it is possible to run them together. See:
https://github.com/putyourlightson/craft-blitz/issues/156

**Comment by khalwat** [comment]
It'll work _once_ when the cache is warmed, but zero analytics will be sent for subsequent cached hits to the pages (which should be the vast majority).

If you're using static caching, you should be using frontend JavaScript for analytics tracking.

**Comment by kaspar-allenbach** [comment]
Darn it you're right.

The commerce funnel setup by your plugin looked so nice 😢
