### ISSUE TITLE
[FR] Disable Live-Preview tracking

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/craft3-instantanalytics#25]
I think live preview is also tracked. Is it possible to disable this?

**Comment by khalwat** [comment]
Good idea

**Comment by khalwat** [comment]
It's such a good idea that it looks like I'm doing it already! :) 

```php
        if ($request->getIsLivePreview()) {
            $this->logExclusion('Craft::$app->getRequest()->getIsLivePreview()');

            return false;
        }
```

https://github.com/nystudio107/craft-instantanalytics/blob/v1/src/services/IA.php#L272
