### ISSUE TITLE
Commerce integration

### ISSUE THREAD

**Issue by pauljohnston** [nystudio107/craft3-instantanalytics#3]
Hi Andrew,

Any updates on Commerce integration?

**Comment by khalwat** [comment]
So I just pushed an update that cleans up the code, and preps it for Commerce.

My plan is to ship Retour, and then circle back to add Commerce integration in Instant Analytics.

I should have it done before Commerce is officially released!

**Comment by andrewcgregory** [comment]
Looking for commerce 2 integration as well. I'll be keeping an eye out for updates!

**Comment by pauljohnston** [comment]
@andrewcgregory We ended up using https://github.com/nystudio107/craft-seomatic as it does everything we needed for analytics plus more.

**Comment by khalwat** [comment]
Keep in mind that SEOmatic doesn't actually send any Commerce analytics on its own; it'll add the appropriate scripts to your pages, but it's up to you to then send the analytics data as appropriate.

**Comment by khalwat** [comment]
Looks like this will be closed next week! :)

**Comment by khalwat** [comment]
If you set your version to `dev-develop` you'll be able to play around with it now!

**Comment by khalwat** [comment]
Craft Commerce 2 support added in Instant Analytics 1.1.0 https://github.com/nystudio107/craft-instantanalytics/releases/tag/1.1.0

@pauljohnston @andrewcgregory

**Comment by williamhibberd** [comment]
Hi Andrew, do you have any updates for commerce 3?
@khalwat

**Comment by khalwat** [comment]
@williamhibberd I'm not aware of any issues with it, but if you have any, feel free to open a new issue here on GitHub

**Comment by williamhibberd** [comment]
Ok, great... I was put using it by the line on the roadmap. Great if it is working on commerce 3!
Thanks
