### ISSUE TITLE
Product List Name (not set) receiving all the Adds to Cart data

### ISSUE THREAD

**Issue by Mellis84** [nystudio107/craft3-instantanalytics#30]
Hi Guys,

On my product listing page I have:

`{% do instantAnalytics.addCommerceProductImpression(product, loop.index, entry.title) %}` In my products loop.

In Analytics, the list names are coming through with Product List Views except for Product Adds To Cart and Product Checkouts data, which all seem to be coming through on a (not set) Product List Name.

Not sure exactly what could be going on here? could be something obvious I am missing?

**Comment by khalwat** [comment]
Can you clarify what you mean here @Mellis84 ? I'm not really understanding the issue you're noting? Perhaps some screenshots would help?
