### ISSUE TITLE
UTM parameters not registered

### ISSUE THREAD

**Issue by arifje** [nystudio107/craft3-instantanalytics#32]
I wanted to track where our sales were coming from by using UTM parameters, but apparently the campaign parameters are not passed to Google Analytics when an order has completed.

I created an URL with the following parameters: ?utm_source=website&utm_medium=blog&utm_campaign=shirts

Then I created a test order with successful payment.

Result in Analytics (via Conversions/Ecommerce/Sales performance):

![Screenshot 2020-07-05 at 15 36 18](https://user-images.githubusercontent.com/1286410/86533983-51541d80-bed5-11ea-93dc-71a3c268f1f5.jpg)

No campaign data stored.

Also, when I look in Acquisition/Campaigns, the campaign is showing up, but no transaction and revenue is related. This should also be the case if I am correct. 

![Screenshot 2020-07-06 at 09 28 35](https://user-images.githubusercontent.com/1286410/86567220-48159000-bf6b-11ea-8942-35aa5e609302.jpg)

Looks like the UTM paramaters are ignored, or I am missing something? 

Craft CMS 3.4.25
Commerce 3.1.10
Instant Analytics 1.1.7

**Comment by khalwat** [comment]
The code is there to handle them: https://github.com/nystudio107/craft-instantanalytics/blob/v1/src/services/IA.php#L449

Can you verify whether it ever reached that portion of the code for you?

**Comment by arifje** [comment]
Yes, it's reaching this part, also setting the parameters correctly:

![Screenshot 2020-07-08 at 10 39 14](https://user-images.githubusercontent.com/1286410/86917500-6f17c180-c125-11ea-84ac-02909a54fdf2.jpg)

But for some reason no campaign data or revenue is popping up in GA.

**Comment by khalwat** [comment]
@skoften I believe you ended up with a solution here?

**Comment by khalwat** [comment]
I think it's possible this could be related to an issue fixed in 1.1.18 -- can you try updating to it?

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-instantanalytics/commit/87bd6a8a077bcc498f4b1959e37621b8c96a4c6e

Can you set your `semver` to `dev-develop` and give it a whirl?

**Comment by khalwat** [comment]
Fix released in 1.1.19 -> https://github.com/nystudio107/craft-instantanalytics/releases/tag/1.1.9

**Comment by arifje** [comment]
thanks, updated the plugin, will let you know the result!
