### ISSUE TITLE
Error adding a Donation to Cart

### ISSUE THREAD

**Issue by antcooper** [nystudio107/craft3-instantanalytics#34]
### Describe the bug
I have setup the Donation under Commerce > Store Settings and [added the sample code](https://docs.craftcms.com/commerce/v3/donations.html#adding-the-donation-to-the-cart) to my Basket page. When I add an amount and submit, I run into errors with Instant Analytics.

It seems the Donation product is an oddity and missing certain parameters that a normal product has, such as Title.

### To reproduce
Steps to reproduce the behaviour:
1. Add  [donation form](https://docs.craftcms.com/commerce/v3/donations.html#adding-the-donation-to-the-cart) to a template. Enter an amount and submit

### Expected behaviour
Item added to Basket. Donation product passed to Analytics

### Versions
- Plugin version: 1.1.7
- Craft version: 3.4.29.1
- Commerce version: 3.1.7

**Comment by khalwat** [comment]
@antcooper Can you get me the error logs produced by IA for this?

**Comment by khalwat** [comment]
Fixed via PR, thanks!
