### ISSUE TITLE
Product List Clicks have null values in GA > Conversions > ecommerce reports

### ISSUE THREAD

**Issue by mikefats** [nystudio107/craft3-instantanalytics#37]
Product **list views** are registering fine through Instant Analytics, as well as Product **detail views**, but not Product **list** **clicks**:

[Google Analytics screenshot](https://share.icloud.com/photos/0XdmNlA86M-6ZKR7yqYWJJmKg)

Am I missing some step in the IA configuration?

**Comment by khalwat** [comment]
@mikefats You need to add a call to `{% do instantAnalytics.addCommerceProductDetailView(PRODUCT_VARIANT) %}` on the page where you're showing a detail view of a product. IA can't automatically know when a product is being displayed unfortunately.

See: https://nystudio107.com/docs/instant-analytics/Using.html#craft-commerce-tracking-with-google-enhanced-ecommerce

**Comment by uaextension** [comment]
Odd. Just like I had the code to report the list views (working correctly)
`{% do instantAnalytics.addCommerceProductImpression(product, loop.index, 'Catalogue search') %}`

My product detail page template has the following code:
`{% do instantAnalytics.addCommerceProductDetailView(product) %}`

so in-line with your suggestion, yet GA's "product list clicks" column in the "Product List Performance" report is all zeros.
I've verified that the 'product' that I'm passing is a valid Craft product item.
