### ISSUE TITLE
Drop in Sessions since installing 1.1.9

### ISSUE THREAD

**Issue by antcooper** [nystudio107/craft3-instantanalytics#44]
We have seen a large drop in GA sessions recently, which coincides with the update to version 1.1.9 from 1.1.7.

I notice that version 1.1.8 contained the fix _Instant Analytics will no longer attempt to create its own clientId..._ and wonder if this could be the cause and if anyone else has reported a change? We have been using IA since the site launch in Jan 2018 and did notice a large increase in traffic quite quickly. We wondered whether some of this could have been related to the above issue too?

Despite me telling the Marketing department to always take GA numbers with a large handful of salt, they are looking for a way to explain the change. It may, of course, be something totally different.

Many thanks, Ant

**Comment by 3dgroup** [comment]
I am currently looking into the same issue!

Big drop in data being passed to google analytics! Zero commerce data going through as well. We did change our server on the same day we noticed a drop in traffic, I did think it was that but now I see another person with the same issue I believe it could be the update we deployed on the same day!

We are definitely getting traffic as google analytics is showing the clicks and we are getting orders! 

@antcooper you speak about getting a lot of extra traffic once you enabled this plugin. So did I, but I pointed this out to be crawler bots. It seems google analytics JS helps avoid this unneeded traffic going to google analytics but Google Analytics Enhanced API gets every bit of data and is not filtered. (I believe this statement to be correct from memory when i was reading about the amount of extra traffic we were seeing after installing this plugin)

**Comment by khalwat** [comment]
It's likely that the drop in session data is that it wasn't properly tracked originally, however if you're *not* using frontend JavaScript tracking, you can set `requireGaCookieClientId` to `false` in the `config.php` which will cause it to revert to the behavior of creating its own `clientId`

@3dgroup you're saying absolutely zero Commerce data is flowing through? This doesn't sound right...
