### ISSUE TITLE
Error when adding a product to cart

### ISSUE THREAD

**Issue by boboldehampsink** [nystudio107/craft3-instantanalytics#5]
I'm using this for the Commerce integration and I'm seeing this error when adding a product to cart:

```
[error][yii\base\ErrorException:2] yii\base\ErrorException: get_class() expects parameter 1 to be object, string given in /app/vendor/nystudio107/craft-instantanalytics/src/services/Commerce.php:477
```

**Comment by khalwat** [comment]
Not sure how a string could end up being passed in there, but will have a look

**Comment by fantasticmachine** [comment]
I have found the cause of the problem, at least in my case.
I had the "Commerce Product Category Field" setting set to a category field type which allowed for multiple category selections. Switching that to use a category field limited to a single category works OK. So my guess is that the plugin is choking when given an array/object containing multiple category relationships.

**Comment by peteeveleigh** [comment]
Scrubbed my comments here and raised a new issue as I'm now thinking it's unrelated.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-instantanalytics/commit/5cdcfafba7d0e63b7ed6e90ac814e711eddfbf01

**Comment by chadcrowell** [comment]
I'm getting this same error. 
Craft CMS 3.1.26
Instant Analytics 1.1.0

https://gist.github.com/chadcrowell/0e40dbe59a871a437782bd3b5693d80d
