### ISSUE TITLE
Purchases missing from GA.

### ISSUE THREAD

**Issue by JacquesFernandes** [nystudio107/craft3-instantanalytics#57]
### Describe the bug
Instant Analytics doesn't send purchase data at times. I *might* have a hunch as to why it's happening, see below (after the divider).

**Note:** I *have* gone through this other [issue](https://github.com/nystudio107/craft-instantanalytics/issues/49) that seems similar, but doesn't seem to apply.

### To reproduce
**(Notable) Plugin Settings:**
- Auto Send PageViews => enabled
- Require GA Cookie clientId => enabled
- Auto Send "Add To Cart" Events => enabled
- Auto Send "Remove From Cart" Events => enabled
- Auto Send "Purchase Complete" Events => enabled

**Questions you might have:**
- Were `_ia`, `_ga` and other GA cookies set?
  - yes

### Expected behaviour
Purchase should go through to Google Analytics, but it isn't.

### Versions
- Plugin version: 1.1.12
- Craft version: 3.6.11.2
- Craft Commerce version: 3.2.17.3

--- 

Something that *might* be relevant is that when I checked `phperrors.log` for the timestamp of the order I found this:
<img width="1289" alt="Screenshot 2021-06-28 at 21 49 59" src="https://user-images.githubusercontent.com/15061702/123703862-dfe74a80-d85c-11eb-87cc-7c5343b32eba.png">

This same set of warnings/errors show up for the other missing purchases but is nowhere to be seen for the purchases that *did* go through to GA.

Thanks a lot for your help in advance, really appreciate it!

**Comment by khalwat** [comment]
@JacquesFernandes Do you have the complete error logs here I could have a look at?

**Comment by khalwat** [comment]
Will re-open if additional information is provided.
