### ISSUE TITLE
Error when navigating to settings page

### ISSUE THREAD

**Issue by boboldehampsink** [nystudio107/craft3-instantanalytics#6]
When going to `/admin/settings/plugins/instant-analytics` I see the following error:

```
Argument 1 passed to craft\services\Fields::getLayoutById() must be of the type int, null given, called in /app/user/vendor/nystudio107/craft-instantanalytics/src/InstantAnalytics.php on line 399
```

I'm using Craft 3.1 with Project Config

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-instantanalytics/commit/905f5c11970719f7ba040bd5fbe14ef25a0b3711

**Comment by peteeveleigh** [comment]
This still seems to be present in a newly installed v1.1.0
The fix isn't in there.

**Comment by khalwat** [comment]
A release hasn't been cut yet, but it will be in the next release.
