### ISSUE TITLE
Server timeout

### ISSUE THREAD

**Issue by philipboomy** [nystudio107/craft3-instantanalytics#63]
### Describe the bug
This is a tricky one. I have had my server time out for 2 months and after working with Craft Support and Ploi support I finally went old school and deactivated add-ons to figure out why it was happening. After deactivating Instant Analytics my server stopped timing out. I can't give you much more than this except it was happening during day and night so not traffic related or Commerce related as there are no orders during night.

The logs gave me nothing except max child setting in NGINX. I upped the max children but didn't fix it.
There are no resource issues and no redirect loops.

### Versions
- Plugin version: 1.1.12
- Craft version: 3.7.16
- PHP 7.4.23

**Comment by khalwat** [comment]
Knowing what IA does, and how it works, it'd be hard to understand how it could be culpable here, but you never know!

If you come up with something more definitive, definitely post it in this thread and I'll revisit it. It's good you made this issue, but there's not much I can do with it at the moment.  Hopefully, you understand.
