### ISSUE TITLE
Event tracking links inside Redactor field

### ISSUE THREAD

**Issue by john-henry** [nystudio107/craft3-instantanalytics#66]
Hi Andrew, this plugin is great. Can't believe I haven't used before to solve some problems. It all does what it says on the box but I have a question regards event tracking for say PDF downloads/eternal links to google docs

its all well and good doing asset/resource tracking for a predetermined part of the template or matrix block say for uploading of assets.

but our client uses Redactor field and links to external assets or docs that we want event tracked

Any ideas on how this may be achieved?

**Comment by khalwat** [comment]
Yeah I'm not sure how to do that, other than if you run the Redactor fields through some kind of search/replace filter that would apply the correct URL to it.
