### ISSUE TITLE
setTitleFromSeomatic error on front-end after plugin install

### ISSUE THREAD

**Issue by Antimated** [nystudio107/craft3-instantanalytics#73]
### Describe the bug
Getting the following error on the front-end after installing the plugin. Quick sidenote: I had the plugin disabled but when deploying the plugin to my staging env the same error was found in my log files (with a server error message being displayed on the front-end as e result)
![Screenshot 2022-09-19 at 10 28 23](https://user-images.githubusercontent.com/2869409/190981154-2df8886b-1af8-4415-a190-e14dfa3360c1.png)

### To reproduce
Steps to reproduce the behaviour:
1. Install plugin
2. View a page on the front-end
3. See error message as displayed in the screenshot above

### Expected behaviour
No error on the front-end

### Versions
- Plugin version: 4.0.0
- Craft version: 4.2.4 (Pro)

**Comment by khalwat** [comment]
So this is probably because the IA settings haven't been filled in... but it still should not barf like this. Will address.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-instantanalytics/commit/e4f44f1bbf3cee9a7f9ccf8cc05e6f7f9f91ade7

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-instantanalytics": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
