### ISSUE TITLE
PayPal transactions are tracking just fine but not SagePay

### ISSUE THREAD

**Issue by mtwalsh** [nystudio107/craft3-instantanalytics#74]
### Describe the bug
In a website that uses both the [PayPal](https://github.com/craftcms/commerce-paypal-checkout/tree/1.3.3) and [SagePay](https://github.com/craftcms/commerce-sagepay/tree/3.0.0) payment gateways, we're noticing e-commerce transactions being recorded for PayPal but not SagePay. Is this an Instant Analytics issue or perhaps something I need to take up with the SagePay payment gateway?

### To reproduce
Steps to reproduce the behaviour:
1. Complete an e-commerce transaction on the site using the PayPal payment gateway
2. Observe e-commerce transaction tracking in Google Analytics for the transaction
3. Complete ... using the SagePay payment gateway
4. Observe no e-commerce transaction tracking ...

### Versions
- Craft Pro: 3.7.53.1
- Craft Commerce: 3.4.17.1
- Instant Analytics: 1.1.15
- PayPal Checkout for Craft Commerce: 1.3.3
- Sage Pay for Craft Commerce: 3.0.0
- SEOmatic: 3.4.37

**Comment by khalwat** [comment]
My guess would be it's specific to SagePay -- but I would think this would be pretty universal, given the events that IA listens to in order to note transations.

**Comment by mtwalsh** [comment]
Thanks for the response, I actually had to remove the IA plugin in the end just because I was not able to get over this issue:

https://github.com/nystudio107/craft-instantanalytics/issues/43

Implementing the e-commerce tracking manually turned out to be the smoother option this time around but it's a shame as the IA plugin would have been great.
