### ISSUE TITLE
What should get passed to addCommerceProductDetailView()

### ISSUE THREAD

**Issue by mylesthedev** [nystudio107/craft3-instantanalytics#75]
### Question
We've been using the V3 of this plugin and upon upgrading to V4 we get a bunch of warnings because `productData['sku']` isn't defined.

What information can we pass this twig function so that it looks for a sku (they do exist on the products variants)?

### Additional context
Use to work fine on version 3 or at least no warning appeared.

**Comment by khalwat** [comment]
Can you post the exact error message you're seeing? I've looked through the code, and it gets the `sku` from the `productVariant`:

```php
            $productData = [
                'sku' => $productVariant->sku,
                'name' => $name,
                'price' => number_format($productVariant->price, 2, '.', ''),
                'category' => $category,
            ];
```

**Comment by Romanavr** [comment]
Hey @khalwat 
I run into the same issue after upgrade to 4.x craft & craft commerce. 
I did some digging and found a bottleneck. Could you check the PR https://github.com/nystudio107/craft-instantanalytics/pull/77 ?

Thanks

**Comment by karensg** [comment]
Hey @khalwat
Could you check the PR please? What do you think?

**Comment by khalwat** [comment]
Looks good, I will merge it in, thanks!

**Comment by khalwat** [comment]
Closed via https://github.com/nystudio107/craft-instantanalytics/pull/77
