### ISSUE TITLE
Undefined array key "sku"

### ISSUE THREAD

**Issue by sarahschuetz** [nystudio107/craft3-instantanalytics#78]
### Describe the bug
When I use `{% do instantAnalytics.addCommerceProductDetailView(product) %}` on the product detail page I get the following error after update from Craft 3 to Craft 4:
`Undefined array key "sku"`

`product` is an object of `craft\commerce\elements\Product` not `craft\commerce\elements\Variant`, so I guess it must be `product['defaultSku']` instead of `product['sku']` in case a product is passed in.

### Versions
- Plugin version: 4.0.2
- Craft version: 4.3.7.1
- Craft Commerce version: 4.2.5.1

**Comment by khalwat** [comment]
This should be fixed in 4.0.3 -> https://github.com/nystudio107/craft-instantanalytics/releases/tag/4.0.3
