### ISSUE TITLE
autoSendPageView sending template path info

### ISSUE THREAD

**Issue by localcraig** [nystudio107/craft3-instantanalytics#80]
### Question

Hey!

We are seeing some template names coming through to google analytics as below:

<img width="275" alt="Screenshot 2023-09-27 at 18 35 05" src="https://github.com/nystudio107/craft-instantanalytics/assets/89455612/6a0780b3-2c95-41c0-8197-8df150bf8fbf">

Rather than the page titles. 

We can see where the issue is coming from as we have **autoSendPageView** on and in the **EVENT_AFTER_RENDER_PAGE_TEMPLATE** event addPageViewEvent() is called with no params so the pageTitle uses InstantAnalytics::$currentTemplate instead. 

Not sure if this is intended or our setup is wrong, any help much appreciated!

Thanks

**Comment by khalwat** [comment]
Are you asking this question on the right repository? This one is for the older Google Analytics, which has since been shut down by Google.
