### ISSUE TITLE
Listed as Missing in the Control Panel

### ISSUE THREAD

**Issue by smockensturm** [nystudio107/craft3-instantanalytics#81]
### Question
Can you tell me why this plugin stubbornly insists on being 'missing' despite being uninstalled, removed and not at all present in `composer.json`.

### Additional context
We don't want it 'missing' we want it removed. We have the GA4 version installed.

**Comment by khalwat** [comment]
It's probably either still in the database or in Project Config for some reason.

**Comment by smockensturm** [comment]
@khalwat It is neither. If the license is still attached to Craft in Craft Console it will continue to show as missing no matter how hard you try to purge it from database, composer, project config or any other place one might suspect.

**Comment by khalwat** [comment]
Crazy. Sorry to hear it was so involved to resolve.
